#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/runtime:6.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["SevDeskConnector/SevDeskConnector.csproj", "SevDeskConnector/"]
COPY ["Airbyte.Cdk/Airbyte.Cdk.csproj", "Airbyte.Cdk/"]
RUN dotnet restore "SevDeskConnector/SevDeskConnector.csproj"
COPY . .
WORKDIR "/src/SevDeskConnector"
RUN dotnet build "SevDeskConnector.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "SevDeskConnector.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "SevDeskConnector.dll"]