name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run:  docker build ./SevDeskConnector/ --tag ghcr.io/airbyte-sevdesk-source-connector:$(date +%s)
    - name: docker loogin
     # env:
      #  DOCKER_USER: ${{ secrets.DOCKER_USER}}
       # DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}
      run: docker login ghcr.io -u fl0wm0ti0n -p ${{ secrets.GITHUB_TOKEN }}
    - name: docker container push
      run: docker push ghcr.io/fl0wm0ti0n/airbyte-sevdesk-source-connector:latest
